### PR TITLE
Added User Profile

### PR DESCRIPTION
**Pull request by corbinhak**

### CODE REVIEW

**Comment by uptonm** [comment]
Before you merge make sure you build and deploy

**Comment by uptonm** [comment]
should just be `npm run deploy` because the `predeploy` script should handle building.

**Comment by corbinhak** [comment]
How would I do this if I edited the file on GitHub directly?

**Comment by uptonm** [comment]
okay not too difficult from here 
1. Clone the repo locally if you havn't already (The actual repo, not a fork)
2. `git checkout add-organizer-corbin`
3. `git pull origin add-organizer-corbin`
4. `npm install`
5. `npm run deploy`

**Comment by uptonm** [comment]
lmk if you have any issues/questions :D

**Pull request merged**
